import type { NextPage } from 'next';
import Head from 'next/head';
import TodoList from '../components/TodoList/TodoList';

const Home: NextPage = () => {
  return (
    <div className="app">
      <Head>
        <title>Todo App</title>
        <meta
          name="Keep track of your activities"
          content="Generated by create next app"
        />
        <link rel="icon" href="/todo.ico" />
      </Head>

      <main className="container">
        <h1 className="head-text">Todo App</h1>
        <TodoList />
      </main>
    </div>
  );
};

export default Home;
